name: itemshopsys pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Setup Java 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "itemshopsys pipeline"
          git config --global init.defaultBranch master
      - name: Grant execute permissions
        run: |
          chmod +x gradlew
      - name: Build itemshopsys plugin
        run: ./gradlew shadowJar --no-daemon
      - name: Upload itemshopsys plugin
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Plugin JAR
          path: itemshopsys-all/build/libs/itemshopsys v*.jar
          if-no-files-found: error